In [25]:
import torch

In [26]:
x = torch.empty(1)
print(x)

tensor([0.])


In [27]:
x = torch.empty(2)
print(x)

tensor([0., 0.])


In [28]:
x = torch.empty(2,3) 
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [29]:
x = torch.empty(2,2,3)
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [30]:
x = torch.rand(2, 3)
print(x)

tensor([[0.7172, 0.7754, 0.0578],
        [0.9516, 0.7642, 0.5629]])


In [31]:
x = torch.zeros(2, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [32]:
print(x.size())
print(x.dtype)

torch.Size([2, 3])
torch.float32


In [33]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
z = x + y
print(z)

tensor([[1.7910, 0.6545],
        [0.8350, 0.4381]])


In [34]:
z = torch.add(x, y)
print(z)

tensor([[1.7910, 0.6545],
        [0.8350, 0.4381]])


In [35]:
x = torch.rand(5,3)
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

tensor([[0.0422, 0.4251, 0.5611],
        [0.8810, 0.6559, 0.6008],
        [0.1904, 0.6296, 0.3278],
        [0.1063, 0.3372, 0.0021],
        [0.1724, 0.4585, 0.3958]])
tensor([0.0422, 0.8810, 0.1904, 0.1063, 0.1724])
tensor([0.8810, 0.6559, 0.6008])
tensor(0.6559)


In [36]:
print(x[1,1].item())

0.6558864116668701


In [37]:
# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available )
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    z.to("cpu")       # ``.to`` can also change dtype together!
    # z = z.numpy()